const DEFAULT_RADIUS_RATIO = 0.55;
const DEFAULT_GAP = 8;
const DEFAULT_ITEM_ASPECT = 1;
const DEFAULT_PERSPECTIVE_FACTOR = 3.5;
const DEFAULT_BACK_OPACITY = 1;
const DEFAULT_BORDER_RADIUS = 16;
const DEFAULT_DRAG_SENSITIVITY = 1;
const MIN_PROJECTION_DENOMINATOR = 1;
const CONTAINER_PADDING = 24;
const IMAGE_FADE_IN_DURATION = 260;
const IMAGE_FADE_IN_SCALE = 1.06;
export {
  CONTAINER_PADDING,
  DEFAULT_BACK_OPACITY,
  DEFAULT_BORDER_RADIUS,
  DEFAULT_DRAG_SENSITIVITY,
  DEFAULT_GAP,
  DEFAULT_ITEM_ASPECT,
  DEFAULT_PERSPECTIVE_FACTOR,
  DEFAULT_RADIUS_RATIO,
  IMAGE_FADE_IN_DURATION,
  IMAGE_FADE_IN_SCALE,
  MIN_PROJECTION_DENOMINATOR,
};
