const DEFAULT_SIZE = 240;
const DEFAULT_COLOR = "#1a73f2";
const DEFAULT_HIGHLIGHT_COLOR = "#fcffff";
const DEFAULT_SPEED = 1;
const DEFAULT_TURBULENCE = 1.2;
const DEFAULT_DETAIL = 1;
const DEFAULT_CONTRAST = 0.8;
const DEFAULT_EDGE_SOFTNESS = 0.01;
const FALLBACK_FRAME_MS = 16;

export {
  DEFAULT_COLOR,
  DEFAULT_CONTRAST,
  DEFAULT_DETAIL,
  DEFAULT_EDGE_SOFTNESS,
  DEFAULT_HIGHLIGHT_COLOR,
  DEFAULT_SIZE,
  DEFAULT_SPEED,
  DEFAULT_TURBULENCE,
  FALLBACK_FRAME_MS,
};
