// Generated by scripts/changelog/index.ts — do not edit by hand.
// Regenerate with `bun run changelog`.

export interface ChangelogEntry {
  label: "Added" | "Fixed" | "Changed" | "Docs";
  scope?: string;
  breaking: boolean;
  subject: string;
  hash: string;
}

export interface ChangelogRelease {
  version: string;
  date: string;
  entries: ChangelogEntry[];
}

export const repositoryUrl = "https://github.com/rit3zh/reacticx";

export const changelog: ChangelogRelease[] = [
  {
    "version": "Unreleased",
    "date": "2026-08-24",
    "entries": [
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add Apple Intelligence and Aura Lift components with shaders and context management",
        "hash": "629cb2e"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add Aurora component with customizable properties and shader effects",
        "hash": "8d64c70"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add BottomSheet component and stack management",
        "hash": "9282f73"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add commit script for streamlined git commits",
        "hash": "ce08c4c"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add community showcase page to highlight projects built with Reacticx",
        "hash": "3dfd052"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add curved text components and staggered text animations",
        "hash": "168201d"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add customizable animated search bar component",
        "hash": "4cb463d"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add Grainy and Mesh Gradient components with shaders",
        "hash": "79c07b4"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add Liquid Metal component documentation and update meta.json",
        "hash": "b237dcf"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add RadiantButton component with customizable styles and animations",
        "hash": "54d64ab"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add Shockwave transition component with Skia shaders",
        "hash": "f747b6d"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add Spectral Wave component with utility functions and documentation",
        "hash": "5426ace"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add squiggly slider component and related types",
        "hash": "ff1a5df"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Add Why Reacticx page with features overview and navigation",
        "hash": "5a0ce7c"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Customise rollingcounter text",
        "hash": "311feab"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Enhance blur effects and add sync watch script",
        "hash": "14f2fc6"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Feat: add SquircleView component with customizable properties",
        "hash": "5b54618"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Implement AnimatedMeshGradient component with customizable properties and shader effects",
        "hash": "dccdbe2"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Implement AnimatedProgressBar component and update registry",
        "hash": "7087a52"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Implement create command for scaffolding new Expo apps with Reacticx",
        "hash": "3e6d900"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Persist fumadocs package manager selection",
        "hash": "b4bc0f8"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Remember most recently used pkg manager",
        "hash": "13f5470"
      },
      {
        "label": "Added",
        "breaking": false,
        "subject": "Update morphing tab bar link and add aurora component to registry",
        "hash": "1103d8b"
      },
      {
        "label": "Added",
        "scope": "docs",
        "breaking": false,
        "subject": "Add new UI and Aura Lift component; remove unused code and assets",
        "hash": "4ee84ef"
      },
      {
        "label": "Added",
        "scope": "mesh-gradient",
        "breaking": false,
        "subject": "Optimize animated mesh gradient with useFrameTime and archive legacy implementation",
        "hash": "e7506e5"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Add vercel.json to set docs as root directory",
        "hash": "9b79af8"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Adjust animation margins and improve mobile layout for TriplePhoneHero component",
        "hash": "a12238b"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "BentoGrid mobile layout responsiveness",
        "hash": "1808b9d"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Correct package name in command strings and update project description",
        "hash": "b1b9d7d"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Enhance file existence check for components in add command",
        "hash": "26a06e1"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Hide Phone Mockups section on mobile devices for better responsiveness",
        "hash": "811fdac"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Jumping search bar",
        "hash": "df6aa20"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Remove deprecated eslint config from next.config.mjs",
        "hash": "04fdf13"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Remove rootDirectory from vercel.json",
        "hash": "10cdffd"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Serve markdown for copy markdown button",
        "hash": "896b46d"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Style name",
        "hash": "5195f0e"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Undo stray semantic-release 1.0.0 bump",
        "hash": "a8dc177"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Update AnimatedBadge styles for improved visual consistency and accessibility",
        "hash": "22329e6"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Update comments and installation instructions for blur-carousel component.",
        "hash": "db05156"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Update component version to 0.1.10 and modify add command to accept optional component name",
        "hash": "66e2b28"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Update documentation link to point to the correct site",
        "hash": "48e06b7"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Update homepage URL and adjust layout styles in landing page and TriplePhoneHero component",
        "hash": "dda2760"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Update homepage URL in package.json",
        "hash": "6bc6035"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Update navigation links to use absolute paths and refactor MobileNav component for improved accessibility",
        "hash": "e2f8367"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Update version to 0.1.4 in package.json",
        "hash": "b808f78"
      },
      {
        "label": "Fixed",
        "scope": "docs",
        "breaking": false,
        "subject": "Add missing dependencies",
        "hash": "efc6558"
      },
      {
        "label": "Fixed",
        "scope": "docs",
        "breaking": false,
        "subject": "Add write permissions to GitHub Actions workflow",
        "hash": "65d7a08"
      },
      {
        "label": "Fixed",
        "scope": "docs",
        "breaking": false,
        "subject": "Ignore TypeScript and ESLint errors during build",
        "hash": "73625ef"
      },
      {
        "label": "Fixed",
        "scope": "docs",
        "breaking": false,
        "subject": "Replace dynamic Date() with static year in footer",
        "hash": "4746cdf"
      },
      {
        "label": "Fixed",
        "scope": "docs",
        "breaking": false,
        "subject": "Update video sources to use external URLs and remove unused media files",
        "hash": "dce7afc"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Add Claude Code skill for using Reacticx components",
        "hash": "d232372"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Add Claude Code skill install command to README",
        "hash": "1e024e5"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Add optimization instruction",
        "hash": "ac817bd"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Add performance optimization",
        "hash": "e04ff59"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Add permissions for semantic-release to push tags and create releases",
        "hash": "2824526"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added new BlurCarousel integration (android)",
        "hash": "c06c34a"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Bump Node.js to v22 for semantic-release compatibility",
        "hash": "95df25e"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Clean up and reorganize registry.json",
        "hash": "f86df1d"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Clean up MeshGradientExample component and remove unnecessary comments",
        "hash": "53c27a7"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Copypaste",
        "hash": "5a8de9f"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Fix JS thread hanging when resuming app",
        "hash": "72e050f"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Fix shockwave registry generation",
        "hash": "6fcbbea"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Fixed docs pages",
        "hash": "4339476"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Refactor component registry: update total components, restructure file organization, and remove unused components",
        "hash": "5fcdc50"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Remove deprecated circular and curved text components from documentation",
        "hash": "80a8172"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Remove deprecated component documentation and update meta.json",
        "hash": "65affdb"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Remove deprecated components and related files from the documentation",
        "hash": "a10df0e"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Remove experimental curved text components and types",
        "hash": "2e335f8"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Remove old loader components and introduce new animated loaders",
        "hash": "37952eb"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Remove outdated deploy workflow and update README for documentation link",
        "hash": "6d0fd09"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Removed unused videos",
        "hash": "9351d52"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Rename version script to bump in package.json [skip cli]",
        "hash": "f97eb95"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Replace @sbaiahmed1/react-native-blur with expo-blur",
        "hash": "ac51ff9"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Revise AI Agent Skill section in README",
        "hash": "251a9e5"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Snapshot full workspace for M5 migration",
        "hash": "1e6b015"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Streamline imports and enhance blur effects across components.",
        "hash": "3768761"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update AI skill section: add GitHub Copilot, fix URL",
        "hash": "fd0503c"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update docs",
        "hash": "bc4c8e4"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update package versions in pnpm-lock.yaml",
        "hash": "df31754"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update project dependencies and improve code structure",
        "hash": "7314338"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update version to 0.1.8 in package.json and enhance component registry structure",
        "hash": "31efd4f"
      },
      {
        "label": "Docs",
        "breaking": false,
        "subject": "Add M5 migration instructions",
        "hash": "54a9e7f"
      },
      {
        "label": "Docs",
        "breaking": false,
        "subject": "Note stray release commit and version check in migration guide",
        "hash": "d189e51"
      }
    ]
  },
  {
    "version": "1.20.3",
    "date": "2026-02-02",
    "entries": [
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Upgrade Node.js to 20 in docs workflow for Next.js compatibility",
        "hash": "94a52b7"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Use --no-frozen-lockfile in GitHub Actions workflows",
        "hash": "fb3b46e"
      }
    ]
  },
  {
    "version": "1.20.2",
    "date": "2026-02-02",
    "entries": [
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Update GitHub Actions workflows to use pnpm",
        "hash": "4fe6658"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Bump version to 1.20.2",
        "hash": "4fcc07d"
      }
    ]
  },
  {
    "version": "1.20.1",
    "date": "2026-02-02",
    "entries": [
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Resolve YAML syntax error in docs workflow",
        "hash": "dfe4eef"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Bump version to 1.20.1",
        "hash": "617ea97"
      }
    ]
  },
  {
    "version": "1.20.0",
    "date": "2026-02-02",
    "entries": [
      {
        "label": "Added",
        "breaking": false,
        "subject": "Complete project transformation from Glow UI to Reacticx",
        "hash": "8d6bdf9"
      },
      {
        "label": "Added",
        "scope": "calendar",
        "breaking": false,
        "subject": "Add new Calendar component",
        "hash": "ea1cb98"
      },
      {
        "label": "Added",
        "scope": "otp-input",
        "breaking": false,
        "subject": "Add new OTP Input component",
        "hash": "25bb17b"
      },
      {
        "label": "Fixed",
        "breaking": false,
        "subject": "Rename 'docs-webste' folder to 'docs-website'",
        "hash": "20482e3"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added a basic pagination component with Gesture Detector 🚀 (Still working on it, not in use…)",
        "hash": "602b68c"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added Animated Segmented Control.",
        "hash": "b851204"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added changes in the documentation website 🚀",
        "hash": "9f37e2f"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added polished README ✨ & Finished the initials. 🚀",
        "hash": "a5dbd33"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added polished README✨",
        "hash": "11b159e"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Enhance app configuration and navigation flow",
        "hash": "bc906b3"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Enhance documentation and component functionality",
        "hash": "3cba3d2"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Fixed Badge component borderRadius property ✨",
        "hash": "43421bb"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Refactor app configuration and update dependencies",
        "hash": "251dd3b"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Refactor components and enhance documentation",
        "hash": "b2be75f"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Refactor Home screen and enhance ExpandableButton component",
        "hash": "d3d27e7"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Remove Breadcrumbs component from both cli and src directories to streamline the codebase.",
        "hash": "50daff8"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Removed unused components.",
        "hash": "3942d57"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update App.tsx to add a date comment for clarity",
        "hash": "726c7b0"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update App.tsx to include a comment indicating changes made",
        "hash": "87d8555"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update docs for action card, button, and dialog",
        "hash": "b7f4c95"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update documentation files for glow-ui version 1.13.2",
        "hash": "20ddc6f"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update Home screen and remove unused files",
        "hash": "2c28576"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update segmented-control.mdx",
        "hash": "b8b601c"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update shimmer component configuration and enhance documentation",
        "hash": "3e04cc9"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Wrapped up the components directory ✨",
        "hash": "ebfbdd5"
      }
    ]
  },
  {
    "version": "1.13.5",
    "date": "2025-06-20",
    "entries": [
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added changes in the documentation website 🚀",
        "hash": "1a7a35f"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added polished README ✨ & Finished the initials. 🚀",
        "hash": "b098e07"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added polished README✨",
        "hash": "1120eac"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Enhance documentation and component functionality",
        "hash": "f867196"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Fixed Badge component borderRadius property ✨",
        "hash": "3cd159b"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update shimmer component configuration and enhance documentation",
        "hash": "c755fd1"
      }
    ]
  },
  {
    "version": "1.13.4",
    "date": "2025-06-09",
    "entries": [
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added polished README✨",
        "hash": "bb0cd2b"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Remove Breadcrumbs component from both cli and src directories to streamline the codebase.",
        "hash": "891ffed"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update documentation files for glow-ui version 1.13.2",
        "hash": "17d0f13"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Wrapped up the components directory ✨",
        "hash": "f94d6db"
      }
    ]
  },
  {
    "version": "1.13.2",
    "date": "2025-05-25",
    "entries": [
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added a basic pagination component with Gesture Detector 🚀 (Still working on it, not in use…)",
        "hash": "5854ad8"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added Animated Segmented Control.",
        "hash": "936c536"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added WhatsNew component (iOS specifically) 🚀",
        "hash": "7a9f49a"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Beta",
        "hash": "7a2c716"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Beta change.",
        "hash": "c41257e"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Crisanne Glow \"App\" Initial commits",
        "hash": "7bea1ed"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "De",
        "hash": "54bce34"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Enhance app configuration and navigation flow",
        "hash": "7474575"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Random",
        "hash": "6b9cdf9"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Refactor App component to implement CustomScrollView with enhanced refresh functionality and options panel. Introduce new styles and update item rendering. Add dialog component exports for better modularity.",
        "hash": "56c58ee"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Refactor app configuration and update dependencies",
        "hash": "1f1c184"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Refactor App structure and add new components including AdBanner (not  component), Timeline, and WhatsNew. Update ESLint configuration and introduce new styles for better UI consistency. 🚀",
        "hash": "4e3987b"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Refactor components and enhance documentation",
        "hash": "329974f"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Refactor Home screen and enhance ExpandableButton component",
        "hash": "fa43513"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Removed unused components.",
        "hash": "07fb6df"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update App.tsx to add a date comment for clarity",
        "hash": "9a2dce1"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update App.tsx to include a comment indicating changes made",
        "hash": "0dddc14"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update Home screen and remove unused files",
        "hash": "682a68c"
      }
    ]
  },
  {
    "version": "1.13.1",
    "date": "2025-05-08",
    "entries": [
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added Avatar & Card & MaskedAnimatedText components 🚀",
        "hash": "f010525"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Fixes... 🚀",
        "hash": "296d41b"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Initial commit: Added core application structure, including artist data handling, UI components, and server setup for API integration. 🚀 (beta)",
        "hash": "cee8c41"
      }
    ]
  },
  {
    "version": "1.11.1",
    "date": "2025-04-28",
    "entries": [
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added feat: Touchable, Ripple, ListItem (not List), BottomSheet (Screen)",
        "hash": "cb9fee1"
      }
    ]
  },
  {
    "version": "1.10.1",
    "date": "2025-04-28",
    "entries": [
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Added feat: Touchable, Ripple, ListItem (not List), BottomSheet (Screen)",
        "hash": "235507b"
      }
    ]
  },
  {
    "version": "1.10.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "3b44405"
      }
    ]
  },
  {
    "version": "1.9.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "9ad9081"
      }
    ]
  },
  {
    "version": "1.8.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "66cbd12"
      }
    ]
  },
  {
    "version": "1.7.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "440c979"
      }
    ]
  },
  {
    "version": "1.6.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "7062172"
      }
    ]
  },
  {
    "version": "1.5.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "92fd669"
      }
    ]
  },
  {
    "version": "1.4.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "673a902"
      }
    ]
  },
  {
    "version": "1.3.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "b7f3758"
      }
    ]
  },
  {
    "version": "1.2.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "d465e84"
      }
    ]
  },
  {
    "version": "1.1.0",
    "date": "2025-04-26",
    "entries": [
      {
        "label": "Added",
        "scope": "button",
        "breaking": false,
        "subject": "Fixed the animation.",
        "hash": "dbcb4d3"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Basics",
        "hash": "9a4fdb6"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "First Commit",
        "hash": "c45a1e4"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "First Initial Commit",
        "hash": "9688509"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Fixes",
        "hash": "73a8a92"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Initial commit",
        "hash": "39445dc"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Remove lockfiles from repo now that they’re in .gitignore",
        "hash": "9f3e299"
      },
      {
        "label": "Changed",
        "breaking": false,
        "subject": "Update .gitignore to include package-lock.json and yarn.lock",
        "hash": "12f26d8"
      }
    ]
  }
];
