import type { WithSpringConfig } from "react-native-reanimated";

const SPRING_CONFIG: WithSpringConfig = {
  damping: 20,
  stiffness: 300,
  mass: 1,
};

const DRAW_DURATION = 900;
const MORPH_DURATION = 550;

const LINE_COLOR = "#4ADE80";
const GRID_COLOR = "rgba(255,255,255,0.08)";
const CURSOR_BORDER_COLOR = "#FFFFFF";

const HORIZONTAL_PADDING = 12;
const VERTICAL_PADDING = 12;

const INDICATOR_RADIUS = 5;
const INDICATOR_BORDER_MULTIPLIER = 1.9;
const PULSE_RADIUS_MULTIPLIER = 4;
const PULSE_DURATION = 1400;
const PULSE_DELAY = 600;

export {
  SPRING_CONFIG,
  DRAW_DURATION,
  MORPH_DURATION,
  LINE_COLOR,
  GRID_COLOR,
  CURSOR_BORDER_COLOR,
  HORIZONTAL_PADDING,
  VERTICAL_PADDING,
  INDICATOR_RADIUS,
  INDICATOR_BORDER_MULTIPLIER,
  PULSE_RADIUS_MULTIPLIER,
  PULSE_DURATION,
  PULSE_DELAY,
};
