const DEFAULT_COLORS = ["#FFFFFF", "#1995FA", "#FFFFFF"];

const DEFAULT_DURATION = 1400;
const DEFAULT_STAGGER = 0.35;
const DEFAULT_PARTICLE_SIZE = 3;
const DEFAULT_DENSITY = 24;
const DEFAULT_MAX_PARTICLES = 3500;
const DEFAULT_DRIFT = 0.6;
const DEFAULT_TOUCH_RADIUS = 60;
const DEFAULT_TOUCH_FORCE = 1;
const DEFAULT_FONT_SIZE = 64;
const SAMPLE_GAP_BASE = 150;
const ALPHA_CUTOFF = 128;
const ATLAS_CELL = 16;
const FIT_RATIO = 0.92;
const SPAWN_RING_MIN = 0.45;
const SPAWN_RING_SPREAD = 0.35;

const SPAWN_SCALE = 0;
const TOUCH_LERP = 0.35;
const DRIFT_SPEED = 0.0022;
const START_DELAY_FRAMES = 2;

export {
  DEFAULT_COLORS,
  DEFAULT_DURATION,
  DEFAULT_STAGGER,
  DEFAULT_PARTICLE_SIZE,
  DEFAULT_DENSITY,
  DEFAULT_MAX_PARTICLES,
  DEFAULT_DRIFT,
  DEFAULT_TOUCH_RADIUS,
  DEFAULT_TOUCH_FORCE,
  DEFAULT_FONT_SIZE,
  SAMPLE_GAP_BASE,
  ALPHA_CUTOFF,
  ATLAS_CELL,
  FIT_RATIO,
  SPAWN_RING_MIN,
  SPAWN_RING_SPREAD,
  SPAWN_SCALE,
  TOUCH_LERP,
  DRIFT_SPEED,
  START_DELAY_FRAMES,
};
