/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Source of truth: cloudflare/landing-assets/
 * Regenerate with: bun run assets:sync
 */

export const LANDING_ASSETS_ORIGIN = "https://cdn.reacticx.com" as const;

export type LandingAssetName =
  | "3d-carousel"
  | "accordion"
  | "action-rail"
  | "alert"
  | "animated-chip"
  | "animated-header-scrollview"
  | "animated-input-bar"
  | "animated-masked-text"
  | "animated-text"
  | "animated-theme-toggle"
  | "apple-intelligence"
  | "arc-list"
  | "aura-lift"
  | "aurora"
  | "avatar"
  | "bar-chart"
  | "barcode-badge"
  | "blur-carousel"
  | "book-page"
  | "border-beam"
  | "bouncy-accordion"
  | "button"
  | "check-box"
  | "chroma-ring"
  | "chrome-backdrop"
  | "cinematic-carousel"
  | "circle-loader"
  | "circular-carousel"
  | "circular-list"
  | "circular-loader"
  | "circular-progress"
  | "circular-text"
  | "context-menu"
  | "coupon"
  | "curved-bottom-tabs"
  | "curved-marquee"
  | "dia-text"
  | "dialog"
  | "disclosure-group"
  | "dust-text"
  | "dynamic-text"
  | "elastic-slider"
  | "energy-orb"
  | "event-ticket-card"
  | "expandable-view"
  | "fade-component"
  | "fade-text"
  | "fan-menu"
  | "filling-stack"
  | "flexi-button"
  | "flip-card"
  | "gooey-popover"
  | "gooey-search-tabs"
  | "gooey-switch"
  | "gooey-text"
  | "gradient-avatar"
  | "gradient-wave-text"
  | "grainy-gradient"
  | "hamburger"
  | "icon-tile"
  | "infinite-menu"
  | "letter-swarm"
  | "line-chart"
  | "liquid-chrome-text"
  | "liquid-metal"
  | "list"
  | "marquee"
  | "masked-tab-bar"
  | "matched-geometry"
  | "material-carousel"
  | "mesh-gradient"
  | "metal"
  | "mobile-dock"
  | "morph-fab"
  | "morph-loader"
  | "morphing-tabbar"
  | "nebula-orb"
  | "number-flow"
  | "orbiting-dots"
  | "otp-input"
  | "pagination"
  | "parallax-carousel"
  | "parallax-header"
  | "photo-stack"
  | "pie-chart"
  | "polaroid"
  | "pressable"
  | "profile-card"
  | "progress"
  | "pulsing-dots"
  | "qr-code"
  | "radar-chart"
  | "radial-chart"
  | "radial-intro"
  | "radiant-button"
  | "range-slider"
  | "receipt-card"
  | "ripple-button"
  | "rolling-counter"
  | "rotate-carousel"
  | "rotating-square"
  | "ruler"
  | "save-button"
  | "scale-carousel"
  | "scrollable-search"
  | "search-bar"
  | "seek-bar"
  | "segmented-control"
  | "shimmer"
  | "shimmer-wave-text"
  | "shockwave"
  | "siri-ios-27"
  | "skia-ripple"
  | "social-button"
  | "spectral-wave"
  | "spin-button"
  | "spinner-arc"
  | "split-view"
  | "squiggly-slider"
  | "squircle-view"
  | "stacked-carousel"
  | "stacked-chips"
  | "staggered-text"
  | "switch"
  | "tabs"
  | "theme-switch"
  | "tilt-carousel"
  | "toast"
  | "toggle"
  | "tray"
  | "unfold-menu"
  | "unstable-orb"
  | "verified-badge"
  | "verified-shine"
  | "vertical-flow-carousel"
  | "vertical-page-carousel"
  | "wave-scrawler";

export interface LandingAsset {
  /** Component slug, derived from the file name. */
  name: LandingAssetName;
  /** Human readable label. */
  title: string;
  /** Original file name on disk. */
  fileName: string;
  /** Whether to render this with a <video> or an <img>. */
  kind: "video" | "image";
  /** MIME type the bucket serves it with. */
  contentType: string;
  /** Object key inside the `reacticx-landing-assets` bucket. */
  bucketKey: string;
  /** Fully qualified public URL. */
  bucketURL: string;
  /** Size in bytes. */
  size: number;
  /** Truncated sha256 of the uploaded file — useful for cache busting. */
  hash: string;
  /** Pixel size, or null when ffprobe could not read the file. */
  width: number | null;
  height: number | null;
  /** width ÷ height. What the gallery weights its row layout by. */
  aspect: number | null;
}

export const landingAssets = [
  {
    name: "3d-carousel",
    title: "3D Carousel",
    fileName: "3d-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "3d-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/3d-carousel-landing-asset.mp4?v=8e981377",
    size: 2662240,
    hash: "8e98137700238da1",
    width: 752,
    height: 844,
    aspect: 0.891,
  },
  {
    name: "accordion",
    title: "Accordion",
    fileName: "accordion-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "accordion-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/accordion-landing-asset.mp4?v=35a0a64f",
    size: 401462,
    hash: "35a0a64fdc4b0756",
    width: 868,
    height: 844,
    aspect: 1.0284,
  },
  {
    name: "action-rail",
    title: "Action Rail",
    fileName: "action-rail-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "action-rail-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/action-rail-landing-asset.mp4?v=14300975",
    size: 127594,
    hash: "143009758394d3d4",
    width: 858,
    height: 438,
    aspect: 1.9589,
  },
  {
    name: "alert",
    title: "Alert",
    fileName: "alert-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "alert-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/alert-landing-asset.png?v=7f6396c8",
    size: 129818,
    hash: "7f6396c857fc3d49",
    width: 740,
    height: 604,
    aspect: 1.2252,
  },
  {
    name: "animated-chip",
    title: "Animated Chip",
    fileName: "animated-chip-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "animated-chip-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/animated-chip-landing-asset.mp4?v=ddae6dc5",
    size: 155688,
    hash: "ddae6dc55a88f08c",
    width: 720,
    height: 494,
    aspect: 1.4575,
  },
  {
    name: "animated-header-scrollview",
    title: "Animated Header Scrollview",
    fileName: "animated-header-scrollview-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "animated-header-scrollview-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/animated-header-scrollview-landing-asset.mp4?v=275e2204",
    size: 346277,
    hash: "275e2204511afb09",
    width: 1218,
    height: 394,
    aspect: 3.0914,
  },
  {
    name: "animated-input-bar",
    title: "Animated Input Bar",
    fileName: "animated-input-bar-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "animated-input-bar-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/animated-input-bar-landing-asset.mp4?v=7be7711e",
    size: 293211,
    hash: "7be7711e76454a8d",
    width: 1228,
    height: 482,
    aspect: 2.5477,
  },
  {
    name: "animated-masked-text",
    title: "Animated Masked Text",
    fileName: "animated-masked-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "animated-masked-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/animated-masked-text-landing-asset.mp4?v=932183b9",
    size: 103064,
    hash: "932183b918642a68",
    width: 716,
    height: 278,
    aspect: 2.5755,
  },
  {
    name: "animated-text",
    title: "Animated Text",
    fileName: "animated-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "animated-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/animated-text-landing-asset.mp4?v=09727ff6",
    size: 251185,
    hash: "09727ff6a8610293",
    width: 682,
    height: 600,
    aspect: 1.1367,
  },
  {
    name: "animated-theme-toggle",
    title: "Animated Theme Toggle",
    fileName: "animated-theme-toggle-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "animated-theme-toggle-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/animated-theme-toggle-landing-asset.mp4?v=4919fc14",
    size: 115444,
    hash: "4919fc1497fc7712",
    width: 720,
    height: 662,
    aspect: 1.0876,
  },
  {
    name: "apple-intelligence",
    title: "Apple Intelligence",
    fileName: "apple-intelligence-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "apple-intelligence-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/apple-intelligence-landing-asset.mp4?v=4a1c4536",
    size: 2586119,
    hash: "4a1c4536bdc73e0f",
    width: 1078,
    height: 894,
    aspect: 1.2058,
  },
  {
    name: "arc-list",
    title: "Arc List",
    fileName: "arc-list-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "arc-list-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/arc-list-landing-asset.mp4?v=cad89363",
    size: 1311928,
    hash: "cad893632710ee44",
    width: 604,
    height: 826,
    aspect: 0.7312,
  },
  {
    name: "aura-lift",
    title: "Aura Lift",
    fileName: "aura-lift-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "aura-lift-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/aura-lift-landing-asset.mp4?v=9f16441f",
    size: 1212344,
    hash: "9f16441fc844ad5e",
    width: 726,
    height: 794,
    aspect: 0.9144,
  },
  {
    name: "aurora",
    title: "Aurora",
    fileName: "aurora-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "aurora-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/aurora-landing-asset.mp4?v=05dad752",
    size: 1317533,
    hash: "05dad752e2e4ba7e",
    width: 906,
    height: 712,
    aspect: 1.2725,
  },
  {
    name: "avatar",
    title: "Avatar",
    fileName: "avatar-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "avatar-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/avatar-landing-asset.png?v=f18283b8",
    size: 94716,
    hash: "f18283b84b692ed9",
    width: 732,
    height: 274,
    aspect: 2.6715,
  },
  {
    name: "bar-chart",
    title: "Bar Chart",
    fileName: "bar-chart-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "bar-chart-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/bar-chart-landing-asset.mp4?v=90355395",
    size: 389430,
    hash: "90355395ef1aa056",
    width: 720,
    height: 532,
    aspect: 1.3534,
  },
  {
    name: "barcode-badge",
    title: "Barcode Badge",
    fileName: "barcode-badge-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "barcode-badge-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/barcode-badge-landing-asset.png?v=50a71ab3",
    size: 41681,
    hash: "50a71ab32319321a",
    width: 504,
    height: 544,
    aspect: 0.9265,
  },
  {
    name: "blur-carousel",
    title: "Blur Carousel",
    fileName: "blur-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "blur-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/blur-carousel-landing-asset.mp4?v=f300441b",
    size: 2052102,
    hash: "f300441b663d3a41",
    width: 932,
    height: 972,
    aspect: 0.9588,
  },
  {
    name: "book-page",
    title: "Book Page",
    fileName: "book-page-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "book-page-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/book-page-landing-asset.png?v=e7d222c7",
    size: 44311,
    hash: "e7d222c77dd28517",
    width: 442,
    height: 567,
    aspect: 0.7795,
  },
  {
    name: "border-beam",
    title: "Border Beam",
    fileName: "border-beam-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "border-beam-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/border-beam-landing-page-asset.mp4?v=10713d2b",
    size: 168946,
    hash: "10713d2b64aeeaa6",
    width: 858,
    height: 320,
    aspect: 2.6812,
  },
  {
    name: "bouncy-accordion",
    title: "Bouncy Accordion",
    fileName: "bouncy-accordion-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "bouncy-accordion-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/bouncy-accordion-landing-page-asset.mp4?v=75f5687d",
    size: 1028334,
    hash: "75f5687da7110372",
    width: 856,
    height: 926,
    aspect: 0.9244,
  },
  {
    name: "button",
    title: "Button",
    fileName: "button-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "button-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/button-landing-asset.mp4?v=3e356eb0",
    size: 107938,
    hash: "3e356eb03388c49a",
    width: 720,
    height: 644,
    aspect: 1.118,
  },
  {
    name: "check-box",
    title: "Check Box",
    fileName: "check-box-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "check-box-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/check-box-landing-asset.mp4?v=97a8d3c3",
    size: 35877,
    hash: "97a8d3c338102eb5",
    width: 478,
    height: 412,
    aspect: 1.1602,
  },
  {
    name: "chroma-ring",
    title: "Chroma Ring",
    fileName: "chroma-ring-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "chroma-ring-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/chroma-ring-landing-asset.mp4?v=200ce4af",
    size: 124815,
    hash: "200ce4af8cc3b5dc",
    width: 752,
    height: 520,
    aspect: 1.4462,
  },
  {
    name: "chrome-backdrop",
    title: "Chrome Backdrop",
    fileName: "chrome-backdrop-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "chrome-backdrop-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/chrome-backdrop-landing-asset.mp4?v=db6f3763",
    size: 1449253,
    hash: "db6f3763bddfd268",
    width: 852,
    height: 482,
    aspect: 1.7676,
  },
  {
    name: "cinematic-carousel",
    title: "Cinematic Carousel",
    fileName: "cinematic-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "cinematic-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/cinematic-carousel-landing-asset.mp4?v=f2f8a72c",
    size: 2203090,
    hash: "f2f8a72c640651ec",
    width: 872,
    height: 662,
    aspect: 1.3172,
  },
  {
    name: "circle-loader",
    title: "Circle Loader",
    fileName: "circle-loader-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "circle-loader-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/circle-loader-landing-asset.mp4?v=336e3e3a",
    size: 31238,
    hash: "336e3e3a852679ae",
    width: 366,
    height: 356,
    aspect: 1.0281,
  },
  {
    name: "circular-carousel",
    title: "Circular Carousel",
    fileName: "circular-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "circular-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/circular-carousel-landing-asset.mp4?v=83e283fb",
    size: 1798515,
    hash: "83e283fbb5234a9b",
    width: 930,
    height: 866,
    aspect: 1.0739,
  },
  {
    name: "circular-list",
    title: "Circular List",
    fileName: "circular-list-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "circular-list-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/circular-list-landing-asset.mp4?v=e17b0448",
    size: 1138287,
    hash: "e17b0448bc2a237c",
    width: 872,
    height: 798,
    aspect: 1.0927,
  },
  {
    name: "circular-loader",
    title: "Circular Loader",
    fileName: "circular-loader-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "circular-loader-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/circular-loader-landing-asset.mp4?v=cc262d57",
    size: 38159,
    hash: "cc262d57dc7b1a78",
    width: 284,
    height: 254,
    aspect: 1.1181,
  },
  {
    name: "circular-progress",
    title: "Circular Progress",
    fileName: "circular-progress-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "circular-progress-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/circular-progress-landing-asset.mp4?v=131a2a96",
    size: 20299,
    hash: "131a2a961d34f595",
    width: 534,
    height: 536,
    aspect: 0.9963,
  },
  {
    name: "circular-text",
    title: "Circular Text",
    fileName: "circular-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "circular-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/circular-text-landing-asset.mp4?v=7c18b105",
    size: 421977,
    hash: "7c18b10553a67d57",
    width: 722,
    height: 662,
    aspect: 1.0906,
  },
  {
    name: "context-menu",
    title: "Context Menu",
    fileName: "context-menu-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "context-menu-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/context-menu-landing-asset.mp4?v=889a49b7",
    size: 427946,
    hash: "889a49b7e75d4747",
    width: 888,
    height: 1716,
    aspect: 0.5175,
  },
  {
    name: "coupon",
    title: "Coupon",
    fileName: "coupon-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "coupon-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/coupon-landing-asset.png?v=06ee2805",
    size: 55616,
    hash: "06ee2805bbc2fccc",
    width: 540,
    height: 566,
    aspect: 0.9541,
  },
  {
    name: "curved-bottom-tabs",
    title: "Curved Bottom Tabs",
    fileName: "curved-bottom-tabs-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "curved-bottom-tabs-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/curved-bottom-tabs-landing-asset.mp4?v=2261fdf0",
    size: 250553,
    hash: "2261fdf0dad7cae2",
    width: 1218,
    height: 804,
    aspect: 1.5149,
  },
  {
    name: "curved-marquee",
    title: "Curved Marquee",
    fileName: "curved-marquee-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "curved-marquee-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/curved-marquee-landing-asset.mp4?v=47b47588",
    size: 1248630,
    hash: "47b475880bb2d145",
    width: 1430,
    height: 622,
    aspect: 2.299,
  },
  {
    name: "dia-text",
    title: "Dia Text",
    fileName: "dia-text-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "dia-text-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/dia-text-landing-page-asset.mp4?v=07736250",
    size: 200483,
    hash: "07736250a671bc72",
    width: 826,
    height: 618,
    aspect: 1.3366,
  },
  {
    name: "dialog",
    title: "Dialog",
    fileName: "dialog-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "dialog-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/dialog-landing-asset.mp4?v=72f15cb2",
    size: 426952,
    hash: "72f15cb274ae1c64",
    width: 712,
    height: 1024,
    aspect: 0.6953,
  },
  {
    name: "disclosure-group",
    title: "Disclosure Group",
    fileName: "disclosure-group-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "disclosure-group-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/disclosure-group-landing-asset.mp4?v=fb3f8c96",
    size: 233205,
    hash: "fb3f8c96b4c33204",
    width: 1116,
    height: 898,
    aspect: 1.2428,
  },
  {
    name: "dust-text",
    title: "Dust Text",
    fileName: "dust-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "dust-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/dust-text-landing-asset.mp4?v=39d205c5",
    size: 504231,
    hash: "39d205c553f3df0d",
    width: 894,
    height: 698,
    aspect: 1.2808,
  },
  {
    name: "dynamic-text",
    title: "Dynamic Text",
    fileName: "dynamic-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "dynamic-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/dynamic-text-landing-asset.mp4?v=0f4a7025",
    size: 83436,
    hash: "0f4a70254b4584bf",
    width: 442,
    height: 360,
    aspect: 1.2278,
  },
  {
    name: "elastic-slider",
    title: "Elastic Slider",
    fileName: "elastic-slider-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "elastic-slider-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/elastic-slider-landing-asset.mp4?v=00e49931",
    size: 79129,
    hash: "00e499316b02da34",
    width: 720,
    height: 676,
    aspect: 1.0651,
  },
  {
    name: "energy-orb",
    title: "Energy Orb",
    fileName: "energy-orb-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "energy-orb-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/energy-orb-landing-asset.mp4?v=fc4ea328",
    size: 634120,
    hash: "fc4ea328ca2852c0",
    width: 794,
    height: 798,
    aspect: 0.995,
  },
  {
    name: "event-ticket-card",
    title: "Event Ticket Card",
    fileName: "event-ticket-card-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "event-ticket-card-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/event-ticket-card-landing-asset.png?v=9cb11298",
    size: 40854,
    hash: "9cb11298e93fbb5a",
    width: 562,
    height: 362,
    aspect: 1.5525,
  },
  {
    name: "expandable-view",
    title: "Expandable View",
    fileName: "expandable-view-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "expandable-view-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/expandable-view-landing-page-asset.mp4?v=2c63bc65",
    size: 907665,
    hash: "2c63bc655498ff1c",
    width: 768,
    height: 848,
    aspect: 0.9057,
  },
  {
    name: "fade-component",
    title: "Fade Component",
    fileName: "fade-component-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "fade-component-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/fade-component-landing-asset.mp4?v=92f97b42",
    size: 44670,
    hash: "92f97b425221773f",
    width: 362,
    height: 328,
    aspect: 1.1037,
  },
  {
    name: "fade-text",
    title: "Fade Text",
    fileName: "fade-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "fade-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/fade-text-landing-asset.mp4?v=e1740c08",
    size: 534510,
    hash: "e1740c0810583793",
    width: 816,
    height: 422,
    aspect: 1.9336,
  },
  {
    name: "fan-menu",
    title: "Fan Menu",
    fileName: "fan-menu-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "fan-menu-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/fan-menu-landing-page-asset.mp4?v=4ebb55f6",
    size: 374958,
    hash: "4ebb55f6faf1c833",
    width: 816,
    height: 1340,
    aspect: 0.609,
  },
  {
    name: "filling-stack",
    title: "Filling Stack",
    fileName: "filling-stack-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "filling-stack-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/filling-stack-landing-asset.mp4?v=5ccb4b3a",
    size: 4261768,
    hash: "5ccb4b3a90b517d3",
    width: 920,
    height: 1102,
    aspect: 0.8348,
  },
  {
    name: "flexi-button",
    title: "Flexi Button",
    fileName: "flexi-button-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "flexi-button-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/flexi-button-landing-asset.mp4?v=8bd13a8f",
    size: 67079,
    hash: "8bd13a8f7b2f0666",
    width: 428,
    height: 398,
    aspect: 1.0754,
  },
  {
    name: "flip-card",
    title: "Flip Card",
    fileName: "flip-card-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "flip-card-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/flip-card-landing-asset.mp4?v=54f702cc",
    size: 642429,
    hash: "54f702cccfabe2df",
    width: 844,
    height: 764,
    aspect: 1.1047,
  },
  {
    name: "gooey-popover",
    title: "Gooey Popover",
    fileName: "gooey-popover-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "gooey-popover-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/gooey-popover-landing-asset.mp4?v=8699299c",
    size: 210763,
    hash: "8699299ce89d7d92",
    width: 808,
    height: 852,
    aspect: 0.9484,
  },
  {
    name: "gooey-search-tabs",
    title: "Gooey Search Tabs",
    fileName: "gooey-search-tabs-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "gooey-search-tabs-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/gooey-search-tabs-landing-asset.mp4?v=dc1cb845",
    size: 112141,
    hash: "dc1cb845c1d34404",
    width: 862,
    height: 308,
    aspect: 2.7987,
  },
  {
    name: "gooey-switch",
    title: "Gooey Switch",
    fileName: "gooey-switch-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "gooey-switch-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/gooey-switch-landing-asset.mp4?v=44d7c8bb",
    size: 375773,
    hash: "44d7c8bb66587a74",
    width: 792,
    height: 796,
    aspect: 0.995,
  },
  {
    name: "gooey-text",
    title: "Gooey Text",
    fileName: "gooey-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "gooey-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/gooey-text-landing-asset.mp4?v=3a2e7559",
    size: 193850,
    hash: "3a2e75599890dd2a",
    width: 628,
    height: 466,
    aspect: 1.3476,
  },
  {
    name: "gradient-avatar",
    title: "Gradient Avatar",
    fileName: "gradient-avatar-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "gradient-avatar-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/gradient-avatar-landing-asset.png?v=3f65ec44",
    size: 97288,
    hash: "3f65ec44f1aee96c",
    width: 810,
    height: 378,
    aspect: 2.1429,
  },
  {
    name: "gradient-wave-text",
    title: "Gradient Wave Text",
    fileName: "gradient-wave-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "gradient-wave-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/gradient-wave-text-landing-asset.mp4?v=98ebb1fd",
    size: 284192,
    hash: "98ebb1fdc0c1d2ef",
    width: 898,
    height: 354,
    aspect: 2.5367,
  },
  {
    name: "grainy-gradient",
    title: "Grainy Gradient",
    fileName: "grainy-gradient-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "grainy-gradient-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/grainy-gradient-landing-asset.mp4?v=8e90c505",
    size: 3874587,
    hash: "8e90c505a99f817e",
    width: 472,
    height: 468,
    aspect: 1.0085,
  },
  {
    name: "hamburger",
    title: "Hamburger",
    fileName: "hamburger-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "hamburger-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/hamburger-landing-asset.mp4?v=2f00ac7d",
    size: 114292,
    hash: "2f00ac7d2c12e9f1",
    width: 754,
    height: 804,
    aspect: 0.9378,
  },
  {
    name: "icon-tile",
    title: "Icon Tile",
    fileName: "icon-tile-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "icon-tile-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/icon-tile-landing-asset.png?v=46d33c01",
    size: 41980,
    hash: "46d33c018637a3a4",
    width: 740,
    height: 260,
    aspect: 2.8462,
  },
  {
    name: "infinite-menu",
    title: "Infinite Menu",
    fileName: "infinite-menu-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "infinite-menu-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/infinite-menu-landing-asset.mp4?v=eed6d5f5",
    size: 1187386,
    hash: "eed6d5f5657d1a89",
    width: 790,
    height: 754,
    aspect: 1.0477,
  },
  {
    name: "letter-swarm",
    title: "Letter Swarm",
    fileName: "letter-swarm-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "letter-swarm-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/letter-swarm-landing-asset.mp4?v=e4862bc2",
    size: 5137037,
    hash: "e4862bc2638db314",
    width: 1068,
    height: 1280,
    aspect: 0.8344,
  },
  {
    name: "line-chart",
    title: "Line Chart",
    fileName: "line-chart-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "line-chart-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/line-chart-landing-asset.mp4?v=8a93814b",
    size: 638992,
    hash: "8a93814bc3556182",
    width: 720,
    height: 608,
    aspect: 1.1842,
  },
  {
    name: "liquid-chrome-text",
    title: "Liquid Chrome Text",
    fileName: "liquid-chrome-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "liquid-chrome-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/liquid-chrome-text-landing-asset.mp4?v=d5ededbb",
    size: 3191376,
    hash: "d5ededbb53ffea78",
    width: 852,
    height: 470,
    aspect: 1.8128,
  },
  {
    name: "liquid-metal",
    title: "Liquid Metal",
    fileName: "liquid-metal-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "liquid-metal-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/liquid-metal-landing-asset.mp4?v=bce0aeba",
    size: 1041180,
    hash: "bce0aebafd4c96cc",
    width: 776,
    height: 804,
    aspect: 0.9652,
  },
  {
    name: "list",
    title: "List",
    fileName: "list-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "list-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/list-landing-asset.png?v=a534729e",
    size: 89850,
    hash: "a534729e250eca5b",
    width: 740,
    height: 592,
    aspect: 1.25,
  },
  {
    name: "marquee",
    title: "Marquee",
    fileName: "marquee-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "marquee-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/marquee-landing-asset.mp4?v=58115848",
    size: 997064,
    hash: "58115848c542f001",
    width: 1336,
    height: 650,
    aspect: 2.0554,
  },
  {
    name: "masked-tab-bar",
    title: "Masked Tab Bar",
    fileName: "masked-tab-bar-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "masked-tab-bar-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/masked-tab-bar-landing-asset.mp4?v=e5e0c4b2",
    size: 184559,
    hash: "e5e0c4b2296b4a51",
    width: 926,
    height: 306,
    aspect: 3.0261,
  },
  {
    name: "matched-geometry",
    title: "Matched Geometry",
    fileName: "matched-geometry-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "matched-geometry-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/matched-geometry-landing-asset.mp4?v=d648ba7f",
    size: 1104249,
    hash: "d648ba7f9a6dc6dd",
    width: 874,
    height: 1078,
    aspect: 0.8108,
  },
  {
    name: "material-carousel",
    title: "Material Carousel",
    fileName: "material-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "material-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/material-carousel-landing-asset.mp4?v=348a56c6",
    size: 2053977,
    hash: "348a56c6af403957",
    width: 910,
    height: 984,
    aspect: 0.9248,
  },
  {
    name: "mesh-gradient",
    title: "Mesh Gradient",
    fileName: "mesh-gradient-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "mesh-gradient-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/mesh-gradient-landing-asset.mp4?v=e9973b3b",
    size: 1146752,
    hash: "e9973b3bc8483c20",
    width: 478,
    height: 472,
    aspect: 1.0127,
  },
  {
    name: "metal",
    title: "Metal",
    fileName: "metal-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "metal-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/metal-landing-asset.mp4?v=dc349a4e",
    size: 294203,
    hash: "dc349a4e93a77339",
    width: 650,
    height: 650,
    aspect: 1,
  },
  {
    name: "mobile-dock",
    title: "Mobile Dock",
    fileName: "mobile-dock-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "mobile-dock-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/mobile-dock-landing-asset.mp4?v=65412a49",
    size: 356959,
    hash: "65412a491b225052",
    width: 876,
    height: 446,
    aspect: 1.9641,
  },
  {
    name: "morph-fab",
    title: "Morph Fab",
    fileName: "morph-fab-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "morph-fab-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/morph-fab-landing-asset.mp4?v=4c855da8",
    size: 93229,
    hash: "4c855da8eaa19070",
    width: 864,
    height: 996,
    aspect: 0.8675,
  },
  {
    name: "morph-loader",
    title: "Morph Loader",
    fileName: "morph-loader-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "morph-loader-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/morph-loader-landing-asset.mp4?v=13915d66",
    size: 369981,
    hash: "13915d66dcd49e13",
    width: 720,
    height: 724,
    aspect: 0.9945,
  },
  {
    name: "morphing-tabbar",
    title: "Morphing Tabbar",
    fileName: "morphing-tabbar-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "morphing-tabbar-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/morphing-tabbar-landing-asset.mp4?v=775e0c6e",
    size: 94916,
    hash: "775e0c6e8b164f89",
    width: 708,
    height: 594,
    aspect: 1.1919,
  },
  {
    name: "nebula-orb",
    title: "Nebula Orb",
    fileName: "nebula-orb-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "nebula-orb-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/nebula-orb-landing-page-asset.mp4?v=70a3d1dd",
    size: 533937,
    hash: "70a3d1dd761609f5",
    width: 772,
    height: 772,
    aspect: 1,
  },
  {
    name: "number-flow",
    title: "Number Flow",
    fileName: "number-flow-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "number-flow-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/number-flow-landing-page-asset.mp4?v=697cd2f6",
    size: 1025603,
    hash: "697cd2f61e27e952",
    width: 828,
    height: 1050,
    aspect: 0.7886,
  },
  {
    name: "orbiting-dots",
    title: "Orbiting Dots",
    fileName: "orbiting-dots-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "orbiting-dots-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/orbiting-dots-landing-asset.mp4?v=f493d0bc",
    size: 42755,
    hash: "f493d0bc0cfa039d",
    width: 372,
    height: 368,
    aspect: 1.0109,
  },
  {
    name: "otp-input",
    title: "OTP Input",
    fileName: "otp-input-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "otp-input-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/otp-input-landing-asset.mp4?v=f6408bae",
    size: 318368,
    hash: "f6408bae811fac2f",
    width: 720,
    height: 272,
    aspect: 2.6471,
  },
  {
    name: "pagination",
    title: "Pagination",
    fileName: "pagination-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "pagination-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/pagination-landing-asset.mp4?v=d68bb6c9",
    size: 70715,
    hash: "d68bb6c92d60e367",
    width: 518,
    height: 490,
    aspect: 1.0571,
  },
  {
    name: "parallax-carousel",
    title: "Parallax Carousel",
    fileName: "parallax-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "parallax-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/parallax-carousel-landing-asset.mp4?v=de73ecf9",
    size: 779038,
    hash: "de73ecf99df0cb73",
    width: 862,
    height: 812,
    aspect: 1.0616,
  },
  {
    name: "parallax-header",
    title: "Parallax Header",
    fileName: "parallax-header-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "parallax-header-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/parallax-header-landing-asset.mp4?v=613fd70d",
    size: 4422210,
    hash: "613fd70d3a897f89",
    width: 904,
    height: 1698,
    aspect: 0.5324,
  },
  {
    name: "photo-stack",
    title: "Photo Stack",
    fileName: "photo-stack-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "photo-stack-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/photo-stack-landing-asset.png?v=d8e476ae",
    size: 278403,
    hash: "d8e476ae97b3c91f",
    width: 594,
    height: 414,
    aspect: 1.4348,
  },
  {
    name: "pie-chart",
    title: "Pie Chart",
    fileName: "pie-chart-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "pie-chart-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/pie-chart-landing-asset.mp4?v=98eae023",
    size: 870039,
    hash: "98eae023a906d813",
    width: 720,
    height: 924,
    aspect: 0.7792,
  },
  {
    name: "polaroid",
    title: "Polaroid",
    fileName: "polaroid-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "polaroid-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/polaroid-landing-asset.png?v=4418c2f2",
    size: 286327,
    hash: "4418c2f2d632fd30",
    width: 534,
    height: 616,
    aspect: 0.8669,
  },
  {
    name: "pressable",
    title: "Pressable",
    fileName: "pressable-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "pressable-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/pressable-landing-asset.mp4?v=2d21de2b",
    size: 86302,
    hash: "2d21de2bf043b921",
    width: 762,
    height: 664,
    aspect: 1.1476,
  },
  {
    name: "profile-card",
    title: "Profile Card",
    fileName: "profile-card-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "profile-card-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/profile-card-landing-asset.png?v=33461a93",
    size: 245077,
    hash: "33461a93b97e63ba",
    width: 538,
    height: 536,
    aspect: 1.0037,
  },
  {
    name: "progress",
    title: "Progress",
    fileName: "progress-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "progress-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/progress-landing-asset.mp4?v=caed05f2",
    size: 163625,
    hash: "caed05f20372f55e",
    width: 812,
    height: 814,
    aspect: 0.9975,
  },
  {
    name: "pulsing-dots",
    title: "Pulsing Dots",
    fileName: "pulsing-dots-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "pulsing-dots-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/pulsing-dots-landing-asset.mp4?v=41b896d7",
    size: 26637,
    hash: "41b896d79f5194f0",
    width: 424,
    height: 444,
    aspect: 0.955,
  },
  {
    name: "qr-code",
    title: "QR Code",
    fileName: "qr-code-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "qr-code-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/qr-code-landing-asset.mp4?v=889d2a12",
    size: 370812,
    hash: "889d2a12ba5effc1",
    width: 720,
    height: 808,
    aspect: 0.8911,
  },
  {
    name: "radar-chart",
    title: "Radar Chart",
    fileName: "radar-chart-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "radar-chart-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/radar-chart-landing-asset.mp4?v=1012a7a1",
    size: 486637,
    hash: "1012a7a1c217203e",
    width: 670,
    height: 690,
    aspect: 0.971,
  },
  {
    name: "radial-chart",
    title: "Radial Chart",
    fileName: "radial-chart-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "radial-chart-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/radial-chart-landing-asset.mp4?v=7af5dcc8",
    size: 1118495,
    hash: "7af5dcc835406989",
    width: 720,
    height: 926,
    aspect: 0.7775,
  },
  {
    name: "radial-intro",
    title: "Radial Intro",
    fileName: "radial-intro-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "radial-intro-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/radial-intro-landing-asset.mp4?v=a229c814",
    size: 1617582,
    hash: "a229c8148334e4c1",
    width: 760,
    height: 1018,
    aspect: 0.7466,
  },
  {
    name: "radiant-button",
    title: "Radiant Button",
    fileName: "radiant-button-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "radiant-button-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/radiant-button-landing-asset.mp4?v=c8bf7f47",
    size: 110681,
    hash: "c8bf7f47ce0d7c0b",
    width: 776,
    height: 608,
    aspect: 1.2763,
  },
  {
    name: "range-slider",
    title: "Range Slider",
    fileName: "range-slider-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "range-slider-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/range-slider-landing-asset.mp4?v=b3550a49",
    size: 126748,
    hash: "b3550a49049434de",
    width: 816,
    height: 436,
    aspect: 1.8716,
  },
  {
    name: "receipt-card",
    title: "Receipt Card",
    fileName: "receipt-card-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "receipt-card-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/receipt-card-landing-asset.png?v=024a3921",
    size: 107175,
    hash: "024a3921930b8fe8",
    width: 560,
    height: 696,
    aspect: 0.8046,
  },
  {
    name: "ripple-button",
    title: "Ripple Button",
    fileName: "ripple-button-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "ripple-button-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/ripple-button-landing-asset.mp4?v=555f2a6c",
    size: 80546,
    hash: "555f2a6c1fde0913",
    width: 334,
    height: 236,
    aspect: 1.4153,
  },
  {
    name: "rolling-counter",
    title: "Rolling Counter",
    fileName: "rolling-counter-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "rolling-counter-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/rolling-counter-landing-asset.mp4?v=adef72a7",
    size: 545908,
    hash: "adef72a738ebdbc5",
    width: 678,
    height: 518,
    aspect: 1.3089,
  },
  {
    name: "rotate-carousel",
    title: "Rotate Carousel",
    fileName: "rotate-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "rotate-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/rotate-carousel-landing-asset.mp4?v=d4fc0ee0",
    size: 670334,
    hash: "d4fc0ee0b5bc7143",
    width: 882,
    height: 992,
    aspect: 0.8891,
  },
  {
    name: "rotating-square",
    title: "Rotating Square",
    fileName: "rotating-square-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "rotating-square-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/rotating-square-landing-asset.mp4?v=925a9608",
    size: 101828,
    hash: "925a9608e8bf4aa6",
    width: 362,
    height: 318,
    aspect: 1.1384,
  },
  {
    name: "ruler",
    title: "Ruler",
    fileName: "ruler-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "ruler-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/ruler-landing-page-asset.mp4?v=385f18c7",
    size: 190368,
    hash: "385f18c7bab74c9b",
    width: 926,
    height: 298,
    aspect: 3.1074,
  },
  {
    name: "save-button",
    title: "Save Button",
    fileName: "save-button-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "save-button-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/save-button-landing-asset.mp4?v=d58d4021",
    size: 78948,
    hash: "d58d4021a3d7e328",
    width: 720,
    height: 382,
    aspect: 1.8848,
  },
  {
    name: "scale-carousel",
    title: "Scale Carousel",
    fileName: "scale-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "scale-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/scale-carousel-landing-asset.mp4?v=95278863",
    size: 3289577,
    hash: "95278863c1072d88",
    width: 928,
    height: 1300,
    aspect: 0.7138,
  },
  {
    name: "scrollable-search",
    title: "Scrollable Search",
    fileName: "scrollable-search-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "scrollable-search-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/scrollable-search-landing-asset.mp4?v=e898e504",
    size: 801237,
    hash: "e898e504f7099852",
    width: 846,
    height: 1178,
    aspect: 0.7182,
  },
  {
    name: "search-bar",
    title: "Search Bar",
    fileName: "search-bar-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "search-bar-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/search-bar-landing-asset.mp4?v=a2e971b5",
    size: 90346,
    hash: "a2e971b5be55bc36",
    width: 832,
    height: 320,
    aspect: 2.6,
  },
  {
    name: "seek-bar",
    title: "Seek Bar",
    fileName: "seek-bar-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "seek-bar-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/seek-bar-landing-asset.mp4?v=11c703bc",
    size: 141486,
    hash: "11c703bc40b7bddd",
    width: 962,
    height: 920,
    aspect: 1.0457,
  },
  {
    name: "segmented-control",
    title: "Segmented Control",
    fileName: "segmented-control-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "segmented-control-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/segmented-control-landing-asset.mp4?v=01c8478e",
    size: 289623,
    hash: "01c8478e74a6a6ea",
    width: 704,
    height: 498,
    aspect: 1.4137,
  },
  {
    name: "shimmer",
    title: "Shimmer",
    fileName: "shimmer-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "shimmer-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/shimmer-landing-asset.mp4?v=52dde29e",
    size: 76438,
    hash: "52dde29e8fab7c8c",
    width: 856,
    height: 570,
    aspect: 1.5018,
  },
  {
    name: "shimmer-wave-text",
    title: "Shimmer Wave Text",
    fileName: "shimmer-wave-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "shimmer-wave-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/shimmer-wave-text-landing-asset.mp4?v=63133778",
    size: 129490,
    hash: "6313377829ba33da",
    width: 692,
    height: 256,
    aspect: 2.7031,
  },
  {
    name: "shockwave",
    title: "Shockwave",
    fileName: "shockwave-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "shockwave-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/shockwave-landing-asset.mp4?v=fa332ddd",
    size: 5604729,
    hash: "fa332ddd887360c9",
    width: 1064,
    height: 1428,
    aspect: 0.7451,
  },
  {
    name: "siri-ios-27",
    title: "Siri IOS 27",
    fileName: "siri-ios-27-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "siri-ios-27-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/siri-ios-27-landing-asset.mp4?v=134c854a",
    size: 468791,
    hash: "134c854a87f2204a",
    width: 746,
    height: 512,
    aspect: 1.457,
  },
  {
    name: "skia-ripple",
    title: "Skia Ripple",
    fileName: "skia-ripple-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "skia-ripple-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/skia-ripple-landing-page-asset.mp4?v=d8df9c7c",
    size: 3445812,
    hash: "d8df9c7cc86ea322",
    width: 800,
    height: 800,
    aspect: 1,
  },
  {
    name: "social-button",
    title: "Social Button",
    fileName: "social-button-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "social-button-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/social-button-landing-asset.png?v=e96bc2f2",
    size: 46490,
    hash: "e96bc2f2f83de7e2",
    width: 516,
    height: 380,
    aspect: 1.3579,
  },
  {
    name: "spectral-wave",
    title: "Spectral Wave",
    fileName: "spectral-wave-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "spectral-wave-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/spectral-wave-landing-asset.mp4?v=b0786cce",
    size: 202625,
    hash: "b0786cce9f754116",
    width: 636,
    height: 468,
    aspect: 1.359,
  },
  {
    name: "spin-button",
    title: "Spin Button",
    fileName: "spin-button-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "spin-button-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/spin-button-landing-asset.mp4?v=2c19e0a7",
    size: 161117,
    hash: "2c19e0a71bd5fea7",
    width: 648,
    height: 498,
    aspect: 1.3012,
  },
  {
    name: "spinner-arc",
    title: "Spinner Arc",
    fileName: "spinner-arc-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "spinner-arc-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/spinner-arc-landing-asset.mp4?v=b09fd2c9",
    size: 29503,
    hash: "b09fd2c998f2f5d8",
    width: 340,
    height: 328,
    aspect: 1.0366,
  },
  {
    name: "split-view",
    title: "Split View",
    fileName: "split-view-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "split-view-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/split-view-landing-page-asset.mp4?v=80f02e36",
    size: 532075,
    hash: "80f02e36b18f9b5b",
    width: 866,
    height: 1328,
    aspect: 0.6521,
  },
  {
    name: "squiggly-slider",
    title: "Squiggly Slider",
    fileName: "squiggly-slider-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "squiggly-slider-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/squiggly-slider-landing-asset.mp4?v=d91919ab",
    size: 406652,
    hash: "d91919ab3916054f",
    width: 874,
    height: 522,
    aspect: 1.6743,
  },
  {
    name: "squircle-view",
    title: "Squircle View",
    fileName: "squircle-view-landing-asset.jpg",
    kind: "image",
    contentType: "image/jpeg",
    bucketKey: "squircle-view-landing-asset.jpg",
    bucketURL: "https://cdn.reacticx.com/squircle-view-landing-asset.jpg?v=6a39a2c7",
    size: 19384,
    hash: "6a39a2c7e2dc56ce",
    width: 477,
    height: 453,
    aspect: 1.053,
  },
  {
    name: "stacked-carousel",
    title: "Stacked Carousel",
    fileName: "stacked-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "stacked-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/stacked-carousel-landing-asset.mp4?v=5ccb4b3a",
    size: 4261768,
    hash: "5ccb4b3a90b517d3",
    width: 920,
    height: 1102,
    aspect: 0.8348,
  },
  {
    name: "stacked-chips",
    title: "Stacked Chips",
    fileName: "stacked-chips-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "stacked-chips-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/stacked-chips-landing-asset.mp4?v=779178ee",
    size: 145823,
    hash: "779178ee4a3c0401",
    width: 770,
    height: 262,
    aspect: 2.9389,
  },
  {
    name: "staggered-text",
    title: "Staggered Text",
    fileName: "staggered-text-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "staggered-text-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/staggered-text-landing-asset.mp4?v=4f53c027",
    size: 457972,
    hash: "4f53c027b0d6546e",
    width: 1166,
    height: 828,
    aspect: 1.4082,
  },
  {
    name: "switch",
    title: "Switch",
    fileName: "switch-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "switch-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/switch-landing-asset.mp4?v=4f97d51f",
    size: 135121,
    hash: "4f97d51f9ade678b",
    width: 736,
    height: 434,
    aspect: 1.6959,
  },
  {
    name: "tabs",
    title: "Tabs",
    fileName: "tabs-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "tabs-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/tabs-landing-asset.mp4?v=3f0ea168",
    size: 119485,
    hash: "3f0ea1689c3bfb32",
    width: 744,
    height: 472,
    aspect: 1.5763,
  },
  {
    name: "theme-switch",
    title: "Theme Switch",
    fileName: "theme-switch-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "theme-switch-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/theme-switch-landing-asset.mp4?v=f1e87615",
    size: 264857,
    hash: "f1e876155522bab4",
    width: 670,
    height: 658,
    aspect: 1.0182,
  },
  {
    name: "tilt-carousel",
    title: "Tilt Carousel",
    fileName: "tilt-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "tilt-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/tilt-carousel-landing-asset.mp4?v=96f4b7c7",
    size: 3004770,
    hash: "96f4b7c76b15be5b",
    width: 918,
    height: 1280,
    aspect: 0.7172,
  },
  {
    name: "toast",
    title: "Toast",
    fileName: "toast-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "toast-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/toast-landing-asset.mp4?v=a7e4fffc",
    size: 705427,
    hash: "a7e4fffcce86a780",
    width: 842,
    height: 328,
    aspect: 2.5671,
  },
  {
    name: "toggle",
    title: "Toggle",
    fileName: "toggle-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "toggle-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/toggle-landing-asset.mp4?v=a90a07b6",
    size: 42610,
    hash: "a90a07b6c6ecb1ca",
    width: 310,
    height: 290,
    aspect: 1.069,
  },
  {
    name: "tray",
    title: "Tray",
    fileName: "tray-landing-page-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "tray-landing-page-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/tray-landing-page-asset.mp4?v=3651349d",
    size: 1699707,
    hash: "3651349d123c1825",
    width: 838,
    height: 1472,
    aspect: 0.5693,
  },
  {
    name: "unfold-menu",
    title: "Unfold Menu",
    fileName: "unfold-menu-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "unfold-menu-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/unfold-menu-landing-asset.mp4?v=25d79708",
    size: 209179,
    hash: "25d79708f297bf2d",
    width: 910,
    height: 720,
    aspect: 1.2639,
  },
  {
    name: "unstable-orb",
    title: "Unstable Orb",
    fileName: "unstable_orb-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "unstable_orb-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/unstable_orb-landing-asset.mp4?v=44375d43",
    size: 559116,
    hash: "44375d43cf53e001",
    width: 748,
    height: 756,
    aspect: 0.9894,
  },
  {
    name: "verified-badge",
    title: "Verified Badge",
    fileName: "verified-badge-landing-asset.png",
    kind: "image",
    contentType: "image/png",
    bucketKey: "verified-badge-landing-asset.png",
    bucketURL: "https://cdn.reacticx.com/verified-badge-landing-asset.png?v=510c3956",
    size: 12760,
    hash: "510c39561f292541",
    width: 380,
    height: 92,
    aspect: 4.1304,
  },
  {
    name: "verified-shine",
    title: "Verified Shine",
    fileName: "verified-shine-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "verified-shine-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/verified-shine-landing-asset.mp4?v=5989548e",
    size: 52222,
    hash: "5989548eecd15e2a",
    width: 730,
    height: 812,
    aspect: 0.899,
  },
  {
    name: "vertical-flow-carousel",
    title: "Vertical Flow Carousel",
    fileName: "vertical-flow-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "vertical-flow-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/vertical-flow-carousel-landing-asset.mp4?v=b5cc066f",
    size: 2653318,
    hash: "b5cc066f54a58f7d",
    width: 910,
    height: 1376,
    aspect: 0.6613,
  },
  {
    name: "vertical-page-carousel",
    title: "Vertical Page Carousel",
    fileName: "vertical-page-carousel-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "vertical-page-carousel-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/vertical-page-carousel-landing-asset.mp4?v=e7910228",
    size: 6081741,
    hash: "e791022840c09308",
    width: 936,
    height: 1482,
    aspect: 0.6316,
  },
  {
    name: "wave-scrawler",
    title: "Wave Scrawler",
    fileName: "wave-scrawler-landing-asset.mp4",
    kind: "video",
    contentType: "video/mp4",
    bucketKey: "wave-scrawler-landing-asset.mp4",
    bucketURL: "https://cdn.reacticx.com/wave-scrawler-landing-asset.mp4?v=9bc69e91",
    size: 4987799,
    hash: "9bc69e91439abedd",
    width: 720,
    height: 1024,
    aspect: 0.7031,
  },
] as const satisfies readonly LandingAsset[];

export const landingAssetsByName = Object.fromEntries(
  landingAssets.map((asset) => [asset.name, asset]),
) as Record<LandingAssetName, LandingAsset>;

export function getLandingAsset(name: LandingAssetName): LandingAsset;
export function getLandingAsset(name: string): LandingAsset | undefined;
export function getLandingAsset(name: string): LandingAsset | undefined {
  return landingAssetsByName[name as LandingAssetName];
}

export function getLandingAssetURL(name: LandingAssetName): string;
export function getLandingAssetURL(name: string): string | undefined;
export function getLandingAssetURL(name: string): string | undefined {
  return getLandingAsset(name)?.bucketURL;
}

export const landingVideos = landingAssets.filter((asset) => asset.kind === "video");
export const landingImages = landingAssets.filter((asset) => asset.kind === "image");
