const DEFAULT_ITEM_HEIGHT = 52;
const UNKNOWN_INDEX = -1;
const DEFAULT_SWEEP = 36;
const MAX_SWEEP = 80;
const MIN_SWEEP = 1;
const HORIZON = Math.PI / 2;
const DEFAULT_MIN_OPACITY = 0.25;
const DEFAULT_MIN_SCALE = 0.78;
const FALLOFF_PLATEAU = 0.45;
const PLATEAU_SCALE = 0.98;
const MIN_RADIUS = 1;
const CENTRE_Z = 1000;
const Z_BAND_LIMIT = 3;
const DEFAULT_FONT_SIZE = 22;
const PROXIMITY_SPAN = 1;
const DEFAULT_INDICATOR_SIZE = 18;
const DEFAULT_INDICATOR_BORDER = 1.4;
const DEFAULT_LABEL_COLOR = "#8a8a8a";
const DEFAULT_ACTIVE_LABEL_COLOR = "#ffffff";
const DEFAULT_INDICATOR_COLOR = "#3d7dff";
const DEFAULT_ACTIVE_INDICATOR_COLOR = "#8e8e93";

export {
  CENTRE_Z,
  Z_BAND_LIMIT,
  DEFAULT_ACTIVE_INDICATOR_COLOR,
  DEFAULT_ACTIVE_LABEL_COLOR,
  DEFAULT_FONT_SIZE,
  DEFAULT_INDICATOR_BORDER,
  DEFAULT_INDICATOR_COLOR,
  DEFAULT_INDICATOR_SIZE,
  DEFAULT_ITEM_HEIGHT,
  DEFAULT_LABEL_COLOR,
  DEFAULT_MIN_OPACITY,
  DEFAULT_MIN_SCALE,
  DEFAULT_SWEEP,
  FALLOFF_PLATEAU,
  HORIZON,
  MAX_SWEEP,
  MIN_RADIUS,
  MIN_SWEEP,
  PLATEAU_SCALE,
  PROXIMITY_SPAN,
  UNKNOWN_INDEX,
};
